### ISSUE TITLE
Many games failing to load

### ISSUE THREAD

**Issue by iguanatamer** [Team-Resurgent/Repackinator#12]
Hi,

I have been having issues with a few titles not loading after converting them with repackinator. I am using the linux cli version. The games that are not working are 007 Nightfire, Counter-Strike, Farcry Instincts, Farcry instincts Evolution and Land of the Dead: Road to Fiddler's Green

**Comment by iguanatamer** [comment]
Tried the UI version too after having to symlink a library and it still didn't work. The ISO MD5s were different though.

**Comment by CaptMoore** [comment]
I have had the same problem, with both the 1.1 and the 1.1 versions of repackinatorui for windows (run by an intel mac under parallels) with the following games: 

ounterstrike
crimson skies
midtown madness 3
phantasy star online
Star WARS BATTLEFRONT
Steel battalion line of contact
unreal championship

As a test, I took the output from Crimson Skies, and tried it, I received a dirty disk error.  I then replaced the default.xbe with a fresh renamed attach.xbe I obtained from driveimageutil 1.0,1 and the iso files played.  Hopefully that helps narrow the search for the bug down somewhat.

**Comment by HoRnEyDvL** [comment]
Thanks for the info will look into it.

**Comment by HoRnEyDvL** [comment]
Can u please see if this fixed the issue?

https://github.com/Team-Resurgent/Repackinator/actions/runs/3536118396

**Comment by iguanatamer** [comment]
No luck :(. Game still shows as a DVD on XBMC4Gamers

**Comment by HoRnEyDvL** [comment]
What Options are u setting in repackinator?

**Comment by HoRnEyDvL** [comment]
Also what version of Cerb are you using ?

**Comment by HoRnEyDvL** [comment]
I just tried doing counterstrike using repackinator unscrubbed image

Name: COUNTER-STRIKE (USA-JPN).1.iso
Size: 3709681664 bytes (3537 MiB)
SHA256: 34BD84027D141F303E422A9703CD8F40C9F332736CE64DA57860B6139B971E65

Name: COUNTER-STRIKE (USA-JPN).2.iso
Size: 3709681664 bytes (3537 MiB)
SHA256: ADE4CECB274FE80232497DFA7EF2E597A166BFE78AB63C21FCFD21B00A5C85E2

Tested on a freshly formatted hdd & booted right up.

No Dirty Disk error or anything.

**Comment by mjkthirdeye** [comment]
Running lastest Repackinator 1.1.1 as of 11-24-2022

Only one I've had trouble with so far is Counter-Strike.
Dirty disc error on launch.

Although I have also tested Tom Clancy's Ghost Recon, including Star Wars Battlefront 1 & 2, Phantasy Star Online as per other reports here, and found those to be working fine.

**Comment by HoRnEyDvL** [comment]
@CaptMoore what bios & version you using ?

**Comment by HoRnEyDvL** [comment]
https://youtu.be/UvaSHCud3cs

**Comment by HoRnEyDvL** [comment]
@CaptMoore @iguanatamer 

Have you tried clearing your saved games?

@mjkthirdeye  was able to get counterstrike working once he removed the save game.

**Comment by mjkthirdeye** [comment]
Thanks to quite a good bit of troubleshooting and help from @HoRnEyDvL, I did manage to get Counter-Strike to load by deleting the game's save data.

What I didn't realize at the time that I reported that finding, however, is that I had also removed the installed DLC along with it. This is now what I believe was actually causing my problem, since copying the old save data back over afterwards didn't seem to affect it.

Having done some more testing. I have found that the problem seems to be caused by the presence of the default.xbe installed by the DLC installer which is found in E/TDATA/4d530036/$u/

If I remove it, the game loads and plays fine.
If I reinstall it, the game fails to load. Also, if try to launch the DLC's default.xbe with the Counter-Strike ISO mounted, I get the same dirty disc error.

**Comment by iguanatamer** [comment]
Still no luck, deleting the saves did not fix the issue. I am on cerbios 2.1.0 Beta and I am using the latest XBMC4Gamers. 

The SHA256 values match the isos so that's not the problem. Here is the SHA256 of the default.xbe launcher: 14dfdb74298b65c66ccbfda194f617839580cae71ceb7416d7c939cddebf1b15

Could the issue derive from a setting in the bios?

**Comment by HoRnEyDvL** [comment]
@iguanatamer Are you on discord by any chance?

https://discord.gg/VcdSfajQGK 

Please join & send a message  will try some realtime support

**Comment by iguanatamer** [comment]
Ok, I will.

**Comment by rizaumami** [comment]
> I have had the same problem, with both the 1.1 and the 1.1.1 versions of repackinatorui for windows (run by an intel mac under parallels) with the following games:
> 
> ounterstrike crimson skies midtown madness 3 phantasy star online Star WARS BATTLEFRONT Steel battalion line of contact unreal championship
> 
> As a test, I took the output from Crimson Skies, and tried it, I received a dirty disk error. I then replaced the default.xbe with a fresh renamed attach.xbe I obtained from driveimageutil 1.0,1 and the iso files played. Hopefully that helps narrow the search for the bug down somewhat.

Can confirm. Halo 2 just went black screen and then rebooted to dashboard. Replace the attacher with driveimageutil's one solve the problem.

**Comment by HoRnEyDvL** [comment]
Ok will look deeper into this issue & return back to you shortly.

**Comment by HoRnEyDvL** [comment]
Multiple sources have confirmed that issue is resolved with latest builds.

**Comment by iguanatamer** [comment]
Still having issues. Land of the dead: road to fiddlers green still does not load.
